### PR TITLE
Healthcheck for HA cloudflare tunnel if connection is dropped

### PR DESCRIPTION
**Pull request by elcajon**
# Proposed Changes

As discussed in #125 this PR implements a small healthcheck using the built-in metrics server.

To summarize the function: 
- Waiting for metrics server to be available (check if cloudflared is up and running, independent of connection status to clouflare edge servers)
- Check if status is 200 (= connected), all fine
- Otherwise increment counter
- Counter = 24 --> reinitialize cloudflared service (send restart command to s6-overlay)
- wait 5 sec

The threshold with 5 sec sleep and 24 loops is set to 120 seconds. I guess this should fit to most environments. 

I was reluctant to include this as a configuration option because the use cases are limited and the add-on configuration is already relatively complex  
What we can think about would be a general option to enable/disable all healthcheck functionality.

## Related Issues

> #125

### CODE REVIEW

**Review by brenner-tobias — APPROVED** [review]
This is awesome. Let's test it for a wile in the Edge repo. Thanks a lot!

**Comment by brenner-tobias** [comment]
since we now have the metrics server, what do you think about also adding it as ingress so you can watch the metrics server from HA @elcajon ?

**Comment by elcajon** [comment]
I also thought about that recently, do you know a suitable template or framework to present the data or do we have to start from scratch?

**Comment by brenner-tobias** [comment]
not really, I was just considering making the standard html of the metrics server available via an ingress rule. Though this is just text and does not look good at all, do you have a better idea?

**Comment by elcajon** [comment]
Not by heart, I will check some resources and Google.

**Pull request merged**
