### PR TITLE
Deprecate 'data_folder'

### PR DESCRIPTION
**Pull request by brenner-tobias**
# Proposed Changes

> Deprecate 'data_folder'

## Related Issues

#191

### CODE REVIEW

**Comment by brenner-tobias** [comment]
I did consider keeping 'data_folder' but it is really not useful without a custom_config from my perspective.
The only thing I am unsure of: Should we include a "migrate_back" flag with a function to migrate the tunnel and certificate files back to the default location or just state that the user should do it?

**Comment by elcajon** [comment]
I would suggest to automatically copy the cert.pem and tunnel.json file from the configured data_path back to /data and showing a warning message. This way should be non disruptive as many users may not know how to access /data paths of add-ons.

**Comment by elcajon** [comment]
Maybe this  "migration" could also be added before removing the configuration options (breaking update), then we just need to reset data_path back to default/blank. This would give users time to raise any errors related to this file moving process.

**Comment by brenner-tobias** [comment]
yeah let's do it that way. I will make a suggestion here

**Comment by brenner-tobias** [comment]
Added a rather harsh solution: If someone is only using 'data_folder' without 'custom_config', the files will be migrated automatically and the option will be removed. Otherwise, the "normal" warning from 'custom_config' will be shown.

**Review by elcajon — APPROVED** [review]
Looks good 👍🏻

**Pull request merged**
