### PR TITLE
Automatically detect HA port

### PR DESCRIPTION
**Pull request by felipecrs**
This simplifies the setup and prevent problems of misconfiguration.

Refs https://github.com/home-assistant/addons/pull/2307

### CODE REVIEW

**Comment by brenner-tobias** [comment]
Great suggestion, I was not aware of the variable "core.port".
I have one doubt though: Why should we still offer to change the port at all? Also, it is technically not correct that the variable default of internal_ha_port is 8123, is it the one that is actually used by HA core.

So my suggestion is to remove the config option completely.
Do you have any thoughts?

**Comment by felipecrs** [comment]
> Why should we still offer to change the port at all?

That's why I removed the option. ;)

**Comment by brenner-tobias** [comment]
Oh right my bad, I thought you only made it optional at first read. Will merge it. Thanks!

**Comment by felipecrs** [comment]
Thank you for the great add-on!

**Pull request merged**
