### PR TITLE
Add data_path funcationality & general maintenance

### PR DESCRIPTION
**Pull request by elcajon**
# Proposed Changes

- Add data_path functionality #43 
- change default config.json path from /data to /tmp #43 
- change default `external_hostname` to "null" so user can't start add-on without adding own value

### CODE REVIEW

**Comment by brenner-tobias** [comment]
Great work @elcajon, thanks a lot.
I am unsure about one thing though: We have to map the additional home assistant folders in the config files anyways (as you did). This does limit the selection of possible folders for the user which he cannot change. Now in the current config, as you correctly mentioned in the documentation, only `ssl` and `share` are possible.

1. I am wondering if it would be better to change `data_path` from a string to list(ssl|share], maybe rename it to `data_folder` or something like that and always use `${data_folder}/cloudflared` for the actual path. 
2. Additionally, it might be a good idea to also include the config folder. This one is from my perspective also looking into the next functionality the best folder to add all the cloudflared files from your computer, since you can easily access it via the file editor add-on.

**Comment by elcajon** [comment]
Good idea, I'll adapt that

**Comment by elcajon** [comment]
I have implemented your suggestions. I have not revised the logic of the migration for the time being, but I think the status should be sufficient for a first version.

**Review by brenner-tobias — APPROVED** [review]
Awesome, feel free to merge

**Pull request merged**
