### PR TITLE
Change hassio_role from admin to manager

### PR DESCRIPTION
**Pull request by elcajon**
Improving add-on security possible by changing hassio_role from admin to manager

# Proposed Changes

manager role should be sufficient for getting nginxproxymanager add-on information

## Related Issues

> ([Github link][autolink-references] to related issues or pull requests)

[autolink-references]: https://help.github.com/articles/autolinked-references-and-urls/

### CODE REVIEW

**Comment by brenner-tobias** [comment]
Did you test this? I tried this when I first introduced the NPM functionality, but it did not work for me. Will check again tonight...

**Comment by pemontto** [comment]
Just tested with `manager` on my PR and it works OK 👍

**Comment by elcajon** [comment]
> Did you test this? I tried this when I first introduced the NPM functionality, but it did not work for me. Will check again tonight...

I checked before creating the PR.

**Comment by brenner-tobias** [comment]
Works for me as well. Really strange, that it did not work for me initially. I must have done something wrong...
Thanks a lot for the PR!

**Pull request closed without merging**
