### PR TITLE
Add Cloudflare backend connectivity check

### PR DESCRIPTION
**Pull request by elcajon**
# Proposed Changes

Since there are always errors due to tunnel disconnections I have implemented a quick and dirty check based on the [information](https://developers.cloudflare.com/cloudflare-one/connections/connect-apps/install-and-setup/ports-and-ips/) from the latest issue (#431).
Also, I didn't implement the messages as a breaking change and they run in the background to not slow down the start of the add-on.

I'm not sure if we should bloat the code with something like this and I wouldn't be angry if we don't implement the change - feel free to tell me what you think.

Checked the change briefly by locking a connection in my UDM:

```
-----------------------------------------------------------
 Add-on: Cloudflared
 Use a Cloudflare Tunnel to remotely connect to Home Assistant without opening any ports
-----------------------------------------------------------
 Add-on version: dev
 You are running the latest version of this add-on.
 System: Home Assistant OS 10.3  (amd64 / qemux86-64)
 Home Assistant Core: 2023.7.1
 Home Assistant Supervisor: 2023.07.1
-----------------------------------------------------------
 Please, share the above information when looking for help
 or support in, e.g., GitHub, forums or the Discord chat.
-----------------------------------------------------------
[21:08:26] INFO: Using Cloudflare Remote Management Tunnel
[21:08:26] INFO: All add-on configuration options except tunnel_token will be ignored.
[21:08:26] INFO: Connecting Cloudflare Tunnel...
2023-07-11T19:08:26Z INF Starting tunnel tunnelID=74e7fcc3-db31-40fd-9a78-fae42bec9cd9
2023-07-11T19:08:26Z INF Version 2023.6.1
2023-07-11T19:08:26Z INF GOOS: linux, GOVersion: go1.19.6, GoArch: amd64
2023-07-11T19:08:26Z INF Settings: map[loglevel:info metrics:0.0.0.0:36500 no-autoupdate:true token:*****]
2023-07-11T19:08:26Z INF Generated Connector ID: 378b7108-2c82-4780-886e-88a53c029b00
2023-07-11T19:08:26Z INF Initial protocol quic
2023-07-11T19:08:26Z INF ICMP proxy will use 172.30.33.4 as source for IPv4
2023-07-11T19:08:26Z INF ICMP proxy will use :: as source for IPv6
2023-07-11T19:08:26Z INF Starting metrics server on [::]:36500/metrics
[21:08:28] WARNING: region2.v2.argotunnel.com TCP port 7844 not reachable
[21:08:29] WARNING: Some necessary services may not be reachable from your host.
[21:08:29] WARNING: Please review lines above and check your firewall/router settings.
2023-07-11T19:08:31Z ERR Failed to create new quic connection error="failed to dial to edge with quic: timeout: no recent network activity" connIndex=0 event=0 ip=198.41.200.113
2023-07-11T19:08:31Z INF Retrying connection in up to 2s connIndex=0 event=0 ip=198.41.200.113
2023-07-11T19:08:36Z ERR Failed to create new quic connection error="failed to dial to edge with quic: timeout: no recent network activity" connIndex=0 event=0 ip=198.41.200.193
2023-07-11T19:08:36Z INF Retrying connection in up to 4s connIndex=0 event=0 ip=198.41.200.193
2023-07-11T19:08:44Z ERR Failed to create new quic connection error="failed to dial to edge with quic: timeout: no recent network activity" connIndex=0 event=0 ip=198.41.200.63
2023-07-11T19:08:44Z INF Retrying connection in up to 8s connIndex=0 event=0 ip=198.41.200.63
```

## Related Issues

#431 
#419 

[autolink-references]: https://help.github.com/articles/autolinked-references-and-urls/

### CODE REVIEW

**Comment by brenner-tobias** [comment]
@elcajon Love it, thanks a lot for the initiative. One thing I am considering: What do you think about introducing a configuration boolean "checkConnectivity" that is false / non existent in default and can be set for trouble shooting connection issues?

That way, properly running tunnels are not affected at all and if there are any breaking changes by Cloudflare in the future, if we recommend to deactivate it after troubleshooting, it will not shoot down all our tunnels.

All of this will of course be reflected well in our documentation

Happy to hear your thoughts.

**Comment by elcajon** [comment]
Counterproposal 😉 
What do you think about (to not introduce another config option that needs to be documented) starting the connectivity check automatically with activation of the debug log mode?

```bashio::debug``` should be perfect for that.

**Comment by brenner-tobias** [comment]
yeah that's even better, let's do it like that

**Review by brenner-tobias — APPROVED** [review]
Awesome

**Comment by elcajon** [comment]
Sorry, added some more debug logging messages. Should be fine now.

**Review by brenner-tobias — APPROVED** [review]

**Pull request merged**
