### PR TITLE
Remove Freenom reference, add wiki link

### PR DESCRIPTION
**Pull request by brenner-tobias**
# Proposed Changes

Since Freenom seems not to be working anymore, we should remove the references to freenom and link to our wiki instead.

### CODE REVIEW

**Review by AlecRust — APPROVED** [review]

**Comment by lin-ycv** [comment]
Can I get a clarification on how the new update affects freenom usage?
I'm using freenom and it works fine, if I update to the new release, would it break?

**Comment by dankarization** [comment]
Also confirming that existing freenom domains are working fine

**Comment by adam-cobb** [comment]
Slightly concerned by this update as I have two instances of HA both using freenom domains in Cloudflare, both working fine currently as the others above. Will hold of any update until we can get some clarification. Thanks.

**Comment by brenner-tobias** [comment]
As you can see in the release notes and also in the code, the removal of Freenom is only a documentation topic, though I agree that this could have been phrased even more clearly. There are numerous reports of people having major issues with Freenom domains, so I removed the part of the documentation that suggest to get a domain from Freenom if you don't have one. I replaced it with the suggestion to buy a cheap one from Namecheap, GoDaddy or any other registar.

So if everything is working now for you, it will continue to work, so you can update without expecting any issues.

**Pull request merged**
