### PR TITLE
Add option in documentation for wildcard DNS record

### PR DESCRIPTION
**Pull request by gerard33**
# Proposed Changes

Add option in documentation for wildcard DNS record as described [here](https://blog.cloudflare.com/wildcard-proxy-for-everyone/).

### CODE REVIEW

**Comment by elcajon** [comment]
In my opinion, the documentation is rather misleading. CNAME records are created automatically by the add-on and do not need to be created manually. Also, using wildcard in combination with additional_hosts is difficult, because there can be overlaps.
I think this is a use case we should not promote via the CLI version of the add-on (local managed tunnel). As in my opinion further testing is needed to ensure the function.

**Comment by gerard33** [comment]
The information I added is meant for the `catch_all_service` and `nginx_proxy_manager` where you have to manually add CNAME records in Cloudflare. This can be skipped when using the wildcard DNS record.
And if you enter an individual CNAME record in Cloudflare than that overrules the wildcard record. I have tested that.

**Comment by elcajon** [comment]
Understood, thanks for the clarification. For me the change fits. Thanks for the contribution. 👍🏼

**Review by brenner-tobias — APPROVED** [review]
Thanks a lot, great addition to the documentation

**Pull request merged**
